global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: clickhouse
    static_configs:
      - targets: [ 'ch-1:8001', 'ch-2:8001', 'ch-3:8001', 'ch-4:8001', 'ch-5:8001', 'ch-6:8001' ]

  - job_name: kafka
    static_configs:
      - targets: [ 'kafka-1:7071', 'kafka-2:7071', 'kafka-3:7071' ]
    tls_config:
      insecure_skip_verify: true
